config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'

  resources :users, only: [:index]
  resources :friend_requests, only: %i[create index update]
  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[new create]
    resources :likes, only: [:create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/friend_request.rb
# frozen_string_literal: true

class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :friend_requests, ->(user) { where(friend_id: user.id, accepted: false) }, foreign_key: :friend_id
  has_many :posts

  def friends
    friend_requests = FriendRequest.where(accepted: true).where('user_id = ? or friend_id = ?', id, id)
    friend_requests.map { |request| request.friend.id == id ? request.user : request.friend }
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parametters, if: :devise_controller?

  protected

  def configure_permitted_parametters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username first_name last_name])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    create_comment
    if params[:action_view] == 'show'
      redirect_to post_path(params[:post_id])
    else
      redirect_to posts_path
    end
  end

  private

  def create_comment
    post = Post.find(params[:post_id])
    post.comments.create!(comment_params)
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/friend_requests_controller.rb
# frozen_string_literal: true

class FriendRequestsController < ApplicationController
  before_action :validate_friend_request, only: [:create]

  def index
    @friend_requests = current_user.friend_requests
  end

  def create
    flash["request-#{friend_id}"] = if @friend_request.save
                                      'Friend request sent'
                                    else
                                      'Friend request can not be sent'
                                    end

    redirect_to users_path
  end

  def update
    friend_request = FriendRequest.find(params[:id])
    friend_request.update(accepted: true)
    redirect_to friend_requests_path
  end

  private

  def validate_friend_request
    @friend_request = FriendRequest.find_or_initialize_by(friend_id:, user_id: current_user.id)
    return unless @friend_request.id.present?

    flash['already-sent-alert'] = 'You already sent a friend request to this user'
    redirect_to users_path
  end

  def friend_id
    @friend_id ||= params[:friend_id]
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    create_like
    if params[:action_view] == 'show'
      redirect_to post_path(params[:post_id])
    else
      redirect_to posts_path
    end
  end

  private

  def create_like
    post = Post.find(params[:post_id])
    post.likes.create!(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = current_user.friends.map(&:posts).flatten.concat(current_user.posts).sort_by(&:created_at)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params.merge!(user_id: current_user.id))
    if @post.save
      redirect_to posts_path
    else
      redirect_to new_post_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:description)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    user_friends = current_user.friends.pluck(:id)
    user_friends << current_user.id
    @users = User.where.not(id: user_friends)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="card rounded-2 mb-2">
  <div class="card-body">
    <h6><%= comment.user.full_name.titlecase %></h6>
    <%= comment.content %>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
  <% if !full_view && post.comments.count > 3  %>
    <%= link_to "Load more comments", post_path(post), class: "mb-3 ms-2" %>
  <% end %>
  
  <div>
    <% if full_view %>
      <% post.comments.order(id: :desc).each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    <% else %>
      <% post.comments.first(3).each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    <% end %>
  </div>

  <%= form_with model: [post, post.comments.build], url: post_comments_path(post, action_view: action_view) do |form| %>
    <div class="form-floating mt-2">
      <%= form.text_area :content, id: "floatingTextarea", class: "w-100 rounded-pill form-control", placeholder: 'Write a comment' %>
      <label for="floatingTextarea">Comment</label>
    </div>
     <%= form.hidden_field :action_view, value: action_view %>
    <div>
      <%= form.submit class: "btn" %>
    </div>
  <% end %>
</div>

app/views/friend_requests/index.html.erb
<%= render 'layouts/header', title: 'Friend requests' %>

<main class="container">
  <div class="row mb-3">
    <h2>Friend requests</h2>
  </div>

  <div class="row">
    <ul class="list-group list-group-flush">
      <% @friend_requests.each do |request| %>
        <li class="list-group-item d-flex align-items-center justify-content-between">
          <label ><%= request.user.full_name.titlecase %></label>
          <%= button_to 'Accept request', friend_request_path(id: request.id), class: "btn", method: :put %>
          <% if flash[:message] %>
            <div style="margin-left: 10px;"><%= flash["request-#{request.id}"] %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</main>

app/views/layouts/_header.html.erb
<header class="p-1">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to 'Odin Facebook', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto me-0">
          <li class="nav-item">
            <%= link_to 'Friend suggestions', users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Friend requests', friend_requests_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Link
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= post.user.full_name.titlecase %></h5>
    <p class="card-text">
      <%= post.description %>
    </p>
  </div>
  <div class="card-footer">
    <div class="row justify-content-between m-2">
      <div class="col-lg-1">
        <label class="card-link">likes: <%= post.likes.count %></label>
      </div>
      <div class="col-lg-2">
        <label class="card-link">comments: <%= post.comments.count %></label>
      </div>
    </div>
    <hr />
    <div class="row m-2">
      <div class="col-12">
        <div class="row align-items-center">
          <div class="col-lg-1">
            <%= button_to 'like', post_likes_path(post_id: post.id, action_view: action_view), class: "btn btn-primary" %>
          </div>
          <div class="col-lg-2">
            <label class="card-link">
              <% if !full_view %>
                <%= link_to 'Comments', post_path(post) %>
              <% end %>
            </label>
          </div>
        </div> 
      </div>
    </div>
    <hr />

    <%= render 'comments/comments', post: post, full_view: full_view, action_view: action_view %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'layouts/header' %>

<main class="container p-2">
  <div class="row">
    <div class="col-10">
      <h2>Posts</h2>
    </div>
    <div class="col-2">
      <%= link_to 'Create Post', new_post_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="mt-5 row">
    <div class="col-10 offset-1">
      <% if @posts.count.zero? %>
        <label>No posts to show</label>
      <% else %>
        <% @posts.each do |post| %>
          <%= render 'post', post: post, full_view: false, action_view: 'index' %>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<%= render 'layouts/header' %>

<div class="container mt-3">
  <div class="row mb-3">
    <h1>New post</h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10"> 
      <%= form_with model: @post do |form| %>
        <div class="mb-3">
          <%= form.label :description, class: "form-label"%> <br>
          <%= form.text_field :description, class: "form-control" %>
        </div>

        <div>
          <%= form.submit class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/header' %>

<main class="container p-2">
  <div>
    <%= render 'post', post: @post, full_view: true, action_view: 'show' %>
  </div>
</main>

app/views/users/index.html.erb
<%= render 'layouts/header', title: 'Friend requests' %>

<main class="container">
  <div class="row mb-3">
    <h2>Friend Suggestions</h2>
  </div>

  <div class="row">
    <ul class="list-group list-group-flush">
      <% @users.each do |user| %>
        <% if flash["request-#{user.id}"].present? %>
          <div class="alert alert-success" role="alert">
            <%= flash["request-#{user.id}"] %>
          </div>
        <% elsif flash['already-sent-alert'].present? %>
          <div class="alert alert-danger" role="alert">
            <%= flash['already-sent-alert'] %>
          </div>
        <% end %>

        <li class="list-group-item d-flex align-items-center justify-content-between">
          <label style="margin-right: 10px"><%= user.full_name.titlecase %></label>
          <%= button_to 'Send friend request', friend_requests_path(friend_id: user.id), class: "btn", method: :post %>
        </li>
      <% end %>
    </ul>
  </div>
</main>